# Generated by Django 3.2.5 on 2023-02-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Branch Id')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Branch Name')),
                ('location', models.TextField(verbose_name='Location')),
                ('seating_capacity', models.PositiveBigIntegerField(verbose_name='Seating Capacity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
