# Generated by Django 3.2.5 on 2023-02-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='location',
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='branch',
            name='province',
            field=models.CharField(max_length=100, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='branch',
            name='street_add',
            field=models.CharField(max_length=100, null=True, verbose_name='Street Address'),
        ),
    ]
