# Generated by Django 3.2.5 on 2023-02-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20230226_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Field'),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number'),
        ),
    ]
