# Generated by Django 3.2.5 on 2023-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Branch Balance'),
        ),
    ]
