# Generated by Django 3.2.5 on 2023-02-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser'),
        ('billing', '0024_alter_sales_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='code',
            field=models.CharField(default='KNupo', editable=False, max_length=5, unique=True, verbose_name='Bill No'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customuser', verbose_name='Billed By'),
        ),
    ]
