# Generated by Django 3.2.5 on 2023-02-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0041_remove_sales_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Create Sale', 'verbose_name_plural': 'Create Sales'},
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='branch',
            new_name='branch_of',
        ),
    ]
