# Generated by Django 3.2.5 on 2023-02-27 05:31

import core.userSession
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0042_auto_20230227_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='branch_of',
            field=models.ForeignKey(default=core.userSession.get_current_user_branch, editable=False, on_delete=django.db.models.deletion.PROTECT, to='branch.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(default=core.userSession.get_current_user, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Billed By'),
        ),
        migrations.AlterField(
            model_name='salesamount',
            name='sales',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='billing.sales', verbose_name='Sales'),
        ),
    ]
