# Generated by Django 3.2.5 on 2023-02-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0043_auto_20230227_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCharges',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Charge Name')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.sales', verbose_name='Sales')),
            ],
            options={
                'verbose_name': 'Additional Charge',
                'verbose_name_plural': 'Additional Charges',
            },
        ),
        migrations.CreateModel(
            name='DiscountAmount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dis_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Amount')),
                ('sales', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='billing.sales', verbose_name='Sales')),
            ],
            options={
                'verbose_name': 'Additional Charge',
                'verbose_name_plural': 'Additional Charges',
            },
        ),
        migrations.AlterModelOptions(
            name='salesamount',
            options={'verbose_name': 'Sale Amount', 'verbose_name_plural': 'Sales Amounts'},
        ),
        migrations.AddField(
            model_name='salesamount',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='default_charge',
            field=models.BooleanField(default=False, verbose_name='Default Charge'),
        ),
        migrations.AddField(
            model_name='taxcharge',
            name='default_charge',
            field=models.BooleanField(default=False, verbose_name='Default Charge'),
        ),
        migrations.DeleteModel(
            name='SalesCharges',
        ),
        migrations.AddField(
            model_name='addcharges',
            name='scharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.servicecharge', verbose_name='Service Charge'),
        ),
    ]
