# Generated by Django 3.2.5 on 2023-02-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0044_auto_20230227_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountamount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='salesitems',
            options={'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
        migrations.RemoveField(
            model_name='addcharges',
            name='name',
        ),
        migrations.AddField(
            model_name='sales',
            name='dis_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Amount'),
        ),
    ]
