# Generated by Django 3.2.5 on 2023-02-27 19:41

import core.userSession
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0045_auto_20230228_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(default=222, primary_key=True, serialize=False)),
                ('g_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Got Amount')),
                ('r_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Returned Amount')),
                ('date', models.DateField(auto_now_add=True, verbose_name='TimeStamp')),
                ('pmethod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.paymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.RemoveField(
            model_name='discountamount',
            name='sales',
        ),
        migrations.AlterField(
            model_name='sales',
            name='dis_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.BigAutoField(default=1311, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='id',
            field=models.BigAutoField(default=2231, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='AddCharges',
        ),
        migrations.DeleteModel(
            name='DiscountAmount',
        ),
        migrations.AddField(
            model_name='payments',
            name='sid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='billing.sales', verbose_name='Sales'),
        ),
        migrations.AddField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(default=core.userSession.get_current_user, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Payment Recieved By'),
        ),
    ]
