# Generated by Django 3.2.5 on 2023-02-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0046_auto_20230228_0126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCharge',
        ),
        migrations.DeleteModel(
            name='TaxCharge',
        ),
        migrations.AlterField(
            model_name='sales',
            name='dis_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Discount Amount'),
        ),
    ]
