# Generated by Django 3.2.5 on 2023-03-01 03:47

import core.userSession
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0048_auto_20230301_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(default=222, primary_key=True, serialize=False)),
                ('g_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Recieved Amount')),
                ('r_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Returned Amount')),
                ('date', models.DateField(auto_now_add=True, verbose_name='TimeStamp')),
                ('pmethod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.paymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.RemoveField(
            model_name='additionalcharges',
            name='default_charge',
        ),
        migrations.RemoveField(
            model_name='taxation',
            name='default_charge',
        ),
        migrations.AddField(
            model_name='sales',
            name='paid_status',
            field=models.BooleanField(default=False, verbose_name='Paid Status'),
        ),
        migrations.AlterField(
            model_name='salesamount',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='salesamount',
            name='gtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Grand Total'),
        ),
        migrations.AlterField(
            model_name='salesamount',
            name='taxable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxable Amount'),
        ),
        migrations.DeleteModel(
            name='SalesItems',
        ),
        migrations.AddField(
            model_name='payments',
            name='sid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='billing.sales', verbose_name='Sales'),
        ),
        migrations.AddField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(default=core.userSession.get_current_user, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Payment Recieved By'),
        ),
    ]
