# Generated by Django 4.1.7 on 2023-03-01 15:57

import core.userSession
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0005_branch_balance"),
        ("billing", "0050_alter_payments_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="branch_of",
            field=models.ForeignKey(
                default=core.userSession.get_current_user_branch,
                on_delete=django.db.models.deletion.PROTECT,
                to="branch.branch",
                verbose_name="Branch",
            ),
        ),
    ]
