# Generated by Django 3.2.5 on 2023-02-26 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
        ('branch', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='5CcxY', max_length=5, unique=True, verbose_name='Order No')),
                ('delivery_location', models.TextField(blank=True, null=True, verbose_name='Delivery Location')),
                ('is_take_away', models.BooleanField(blank=True, default=False, verbose_name='Take away Order')),
                ('completion_status', models.BooleanField(default=False, verbose_name='Completed')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_name', to='branch.branch', verbose_name='Branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Customer')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_name', to='branch.branch', verbose_name='Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Order Opened By')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('timestamp', models.DateTimeField(verbose_name='Time Stamp')),
                ('status', models.TextField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('IP', 'In Progress'), ('R', 'Ready'), ('D', 'Delivered'), ('CC', 'Cancelled')], max_length=10, verbose_name='Order Choices')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitems', verbose_name='Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Order taken by')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
