# Generated by Django 3.2.5 on 2023-02-26 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0020_alter_order_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='branch',
            new_name='branch_of',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user_add',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Order Opened By'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='user_add',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Order taken by'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='VxoYv', editable=False, max_length=5, unique=True, verbose_name='Order No'),
        ),
    ]
