# Generated by Django 3.2.5 on 2023-02-26 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20230226_1123'),
        ('order', '0023_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branch_of',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_name', to='branch.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='7rLoM', editable=False, max_length=5, unique=True, verbose_name='Order No'),
        ),
    ]
