# Generated by Django 3.2.5 on 2023-02-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser'),
        ('order', '0024_auto_20230226_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='SDEjZ', editable=False, max_length=5, unique=True, verbose_name='Order No'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_add',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.customuser', verbose_name='Order Opened By'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='user_add',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.customuser', verbose_name='Order taken by'),
        ),
    ]
