# Generated by Django 3.2.5 on 2023-02-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20230226_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='Fsw9Q', editable=False, max_length=5, unique=True, verbose_name='Order No'),
        ),
    ]
