# Generated by Django 3.2.5 on 2023-02-26 12:02

import core.userSession
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20230226_1123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0028_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branch_of',
            field=models.ForeignKey(default=core.userSession.get_current_user_branch, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_name', to='branch.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='VAS8V', editable=False, max_length=5, unique=True, verbose_name='Order No'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_add',
            field=models.ForeignKey(default=core.userSession.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Order Opened By'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='user_add',
            field=models.ForeignKey(default=core.userSession.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Order taken by'),
        ),
    ]
