# Generated by Django 3.2.5 on 2023-02-26 12:53

import core.userSession
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20230226_1123'),
        ('order', '0037_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branch_of',
            field=models.ForeignKey(default=core.userSession.get_current_user_branch, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='branch_name', to='branch.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='XaZre', editable=False, max_length=5, unique=True, verbose_name='Order No'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='status',
            field=models.TextField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('IP', 'In Progress'), ('R', 'Ready'), ('D', 'Delivered'), ('CC', 'Cancelled')], default='P', max_length=10, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp'),
        ),
    ]
