# Generated by Django 3.2.5 on 2023-02-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_auto_20230226_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='Cmiwh', editable=False, max_length=5, unique=True, verbose_name='Order No'),
        ),
    ]
