# Generated by Django 3.2.5 on 2023-02-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_alter_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
    ]
