# Generated by Django 3.2.5 on 2023-02-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_alter_tablecategory_branch_of'),
        ('order', '0042_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_name', to='table.tablename', verbose_name='Table'),
        ),
    ]
