# Generated by Django 3.2.5 on 2023-02-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_alter_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_take_away',
        ),
    ]
