# Generated by Django 3.2.5 on 2023-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_auto_20230227_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Total'),
        ),
    ]
