# Generated by Django 3.2.5 on 2023-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_orderitems_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(default=231, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='id',
            field=models.BigAutoField(default=111, primary_key=True, serialize=False),
        ),
    ]
