# Generated by Django 3.2.5 on 2023-03-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_alter_orderitems_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='status',
        ),
    ]
