# Generated by Django 3.2.5 on 2023-02-26 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20230226_1123'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablecategory',
            name='branch',
        ),
        migrations.AddField(
            model_name='tablecategory',
            name='branch_of',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch', verbose_name='Branch'),
        ),
    ]
