# Generated by Django 3.2.5 on 2023-02-26 12:02

import core.userSession
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20230226_1123'),
        ('table', '0004_alter_tablecategory_branch_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecategory',
            name='branch_of',
            field=models.ForeignKey(blank=True, default=core.userSession.get_current_user_branch, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch', verbose_name='Branch'),
        ),
    ]
