# Generated by Django 3.2.5 on 2023-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_alter_tablecategory_branch_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablename',
            name='res_status',
            field=models.BooleanField(default=False, verbose_name='Reserved/Taken'),
        ),
    ]
